# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a2087c36b3d88c748e9e2339ebab5527"
name = "PriceFlow"
application_url = "https://app.teszt.uk"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "priceflow-dev.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "http://localhost:4000/api/auth/callback",
  "https://app.teszt.uk/api/auth/callback"
]
