api_version = "2026-01"
uid = "7bc196f3-1425-76f2-ecc0-47efee71d8c02ddd7f28"
type = "theme"
name = "PriceFlow Widget"

[[extensions]]
type = "theme"
name = "PriceFlow Konfigurátor"
handle = "priceflow-widget"

  [[extensions.blocks]]
  type = "app"
  name = "PriceFlow Konfigurátor"

    [[extensions.blocks.settings]]
    type = "text"
    id = "widget_url"
    label = "Widget URL"
    default = "https://d1kl8ffas839mv.cloudfront.net"

    [[extensions.blocks.settings]]
    type = "range"
    id = "widget_height"
    min = 300
    max = 800
    step = 50
    unit = "px"
    label = "Widget magasság"
    default = 500
