tunnel: c0514172-f50b-4390-9d81-637b4d165d9d
credentials-file: /etc/cloudflared/c0514172-f50b-4390-9d81-637b4d165d9d.json

ingress:
  - hostname: app.teszt.uk
    service: http://nginx:80
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      disableChunkedEncoding: false
  - service: http_status:404